name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Fixes'
    labels: ['fix', 'bug', 'bugfix']
  - title: '🧹 Chore'
    labels: ['chore', 'refactor', 'deps']
  - title: '📚 Docs'
    labels: ['docs']
  - title: '⚙️ CI/CD'
    labels: ['ci', 'build']

change-template: |
  - $TITLE (#$NUMBER) @$AUTHOR

change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels: ['major']
  minor:
    labels: ['minor', 'feature']
  patch:
    labels: ['patch', 'fix', 'bug', 'bugfix']
  default: patch

template: |
  ## What’s Changed
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
